version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=zefirula
    volumes: 
      - pgdata:/data/postgres

  app:
    container_name: zefirula-api-container
    image: node
    working_dir: /usr/src/zefirula-api
    restart: always
    command: bash -c "npm install && npm run dev"
    volumes:
      - .:/usr/src/zefirula-api
    ports: 
      - 3333:3333
    links: 
      - postgres

volumes: 
  pgdata: